import { useState, type ReactNode } from "react";
import { BarChart3, Bell, Box, ChevronDown, CircleDollarSign, ClipboardList, FileText, Gauge, LayoutDashboard, Menu, Package, Search, Settings, ShoppingCart, Target, TrendingUp, Users, X, Zap } from "lucide-react";
import { Link, NavLink, Outlet, useLocation } from "react-router-dom";
import { Button, Card, Input } from "../components/ui";
import { formatCurrency } from "../lib/utils";

const menu = [
  [LayoutDashboard, "Dashboard", "/admin"], [Box, "Products", "/admin/products"], [ShoppingCart, "Orders", "/admin/orders"],
  [Users, "Customers", "/admin/customers"], [FileText, "Quotes", "/admin/quotes"], [Target, "Leads", "/admin/leads"],
  [BarChart3, "Analytics", "/admin/analytics"], [Gauge, "Sales Targets", "/admin/targets"], [Settings, "Settings", "/admin/settings"],
] as const;

export function AdminLayout() {
  const [open, setOpen] = useState(false);
  const location = useLocation();
  const current = menu.find((item) => item[2] === location.pathname)?.[1] || "Dashboard";
  return <div className="min-h-screen bg-[#050914] text-slate-200"><aside className={`fixed inset-y-0 left-0 z-[80] w-64 border-r border-line bg-[#07101e] p-4 transition lg:translate-x-0 ${open ? "translate-x-0" : "-translate-x-full"}`}><div className="flex items-center justify-between px-2 py-3"><Link to="/" className="flex items-center gap-3 font-extrabold text-white"><span className="grid h-9 w-9 place-items-center rounded-lg bg-blue-600"><Zap className="h-5 w-5" /></span>PaceMaker</Link><button className="lg:hidden" onClick={() => setOpen(false)}><X /></button></div><p className="mb-3 mt-7 px-3 text-[10px] font-bold uppercase tracking-[.22em] text-slate-600">Operations</p><nav className="space-y-1">{menu.map(([Icon, label, path]) => <NavLink end key={path} to={path} onClick={() => setOpen(false)} className={({ isActive }) => `flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium transition ${isActive ? "bg-blue-600 text-white shadow-lg shadow-blue-950" : "text-slate-500 hover:bg-slate-800 hover:text-white"}`}><Icon className="h-4 w-4" />{label}</NavLink>)}</nav><div className="absolute bottom-4 left-4 right-4 rounded-xl border border-line bg-slate-950/50 p-4"><p className="text-xs font-bold text-white">Admin Demo</p><p className="mt-1 text-[11px] text-slate-600">Frontend operations workspace</p><Link to="/" className="mt-3 block text-xs font-semibold text-blue-400">Return to storefront →</Link></div></aside>{open && <button className="fixed inset-0 z-[70] bg-black/60 lg:hidden" onClick={() => setOpen(false)} aria-label="Close sidebar" />}<div className="lg:pl-64"><header className="sticky top-0 z-40 flex h-[72px] items-center justify-between border-b border-line bg-[#050914]/90 px-4 backdrop-blur-xl sm:px-7"><div className="flex items-center gap-3"><button onClick={() => setOpen(true)} className="rounded-lg p-2 text-slate-400 lg:hidden"><Menu /></button><div><h1 className="font-bold text-white">{current}</h1><p className="hidden text-xs text-slate-600 sm:block">Sunday, June 14, 2026</p></div></div><div className="flex items-center gap-2"><div className="relative hidden md:block"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-600" /><Input className="h-9 w-64 pl-9" placeholder="Search operations" /></div><button className="relative rounded-xl border border-line p-2.5 text-slate-400"><Bell className="h-4 w-4" /><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-orange-500" /></button><button className="flex items-center gap-2 rounded-xl border border-line p-1.5 pr-3"><span className="grid h-7 w-7 place-items-center rounded-lg bg-blue-600 text-xs font-bold">AK</span><ChevronDown className="h-3 w-3 text-slate-500" /></button></div></header><main className="p-4 sm:p-7"><Outlet /></main></div></div>;
}

const metrics = [[CircleDollarSign, "Revenue this month", "₹37,50,000", "+12.4%", "text-emerald-400"], [ShoppingCart, "Orders", "184", "+8.1%", "text-blue-400"], [Users, "New customers", "67", "+15.3%", "text-violet-400"], [Target, "Qualified leads", "92", "+6.8%", "text-orange-400"]] as const;

export function AdminDashboard() {
  return <div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([Icon, label, value, change, color]) => <Card key={label} className="p-5"><div className="flex items-center justify-between"><span className={`grid h-10 w-10 place-items-center rounded-xl bg-slate-950 ${color}`}><Icon className="h-5 w-5" /></span><span className="rounded-full bg-emerald-500/10 px-2 py-1 text-[11px] text-emerald-400">{change}</span></div><p className="mt-5 text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-extrabold text-white">{value}</p></Card>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-[1.5fr_.8fr]"><RevenueChart /><TargetCard /></div><div className="mt-5 grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><RecentOrders /><TopProducts /></div></div>;
}

function RevenueChart() {
  const values = [36, 48, 42, 61, 56, 75, 68, 87, 73, 92, 84, 100];
  return <Card className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-bold text-white">Revenue performance</h2><p className="mt-1 text-xs text-slate-600">Monthly sales, FY 2025–26</p></div><select className="rounded-lg border border-line bg-slate-950 p-2 text-xs text-slate-400"><option>Last 12 months</option></select></div><div className="mt-8 flex h-56 items-end gap-2 border-b border-line sm:gap-4">{values.map((value, index) => <div key={index} className="group flex h-full flex-1 items-end"><div className="relative w-full rounded-t-md bg-gradient-to-t from-blue-700 to-blue-400 transition hover:from-orange-600 hover:to-orange-400" style={{ height: `${value}%` }}><span className="absolute -top-6 left-1/2 hidden -translate-x-1/2 text-[10px] text-white group-hover:block">₹{Math.round(value / 2)}L</span></div></div>)}</div><div className="mt-3 flex justify-between text-[10px] text-slate-700"><span>Jul</span><span>Sep</span><span>Nov</span><span>Jan</span><span>Mar</span><span>Jun</span></div></Card>;
}

function TargetCard() {
  return <Card className="p-5 sm:p-6"><h2 className="font-bold text-white">Annual sales target</h2><p className="mt-1 text-xs text-slate-600">FY 2025–26</p><div className="mx-auto mt-7 grid h-40 w-40 place-items-center rounded-full" style={{ background: "conic-gradient(#2563eb 0 75%, #172033 75% 100%)" }}><div className="grid h-28 w-28 place-items-center rounded-full bg-panel text-center"><div><strong className="text-3xl text-white">75%</strong><p className="text-[10px] text-slate-600">ACHIEVED</p></div></div></div><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-950/60 p-3"><p className="text-[10px] text-slate-600">Target</p><p className="mt-1 font-bold text-white">₹50,00,000</p></div><div className="rounded-xl bg-slate-950/60 p-3"><p className="text-[10px] text-slate-600">Achieved</p><p className="mt-1 font-bold text-blue-400">₹37,50,000</p></div></div></Card>;
}

function RecentOrders() {
  const rows = [["PM-260614", "ABC Textiles", "Servo Stabilizer", "₹53,100", "Processing"], ["PM-260613", "NovaCare Hospitals", "Isolation Transformer", "₹3,77,600", "Confirmed"], ["PM-260611", "Orion Foods", "APFC Panel", "₹1,05,020", "Dispatched"], ["PM-260608", "Axion Auto", "MCC Panel", "₹4,72,000", "Delivered"]];
  return <Card className="overflow-hidden"><div className="flex items-center justify-between p-5"><h2 className="font-bold text-white">Recent orders</h2><Link to="/admin/orders" className="text-xs text-blue-400">View all</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="border-y border-line bg-slate-950/40 text-slate-600"><tr>{["Order", "Customer", "Product", "Value", "Status"].map((h) => <th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row[0]} className="border-b border-line last:border-0">{row.map((cell, index) => <td key={cell} className={`px-5 py-4 ${index === 0 ? "font-bold text-blue-400" : index === 4 ? "text-emerald-400" : "text-slate-400"}`}>{cell}</td>)}</tr>)}</tbody></table></div></Card>;
}

function TopProducts() {
  return <Card className="p-5"><h2 className="font-bold text-white">Top products</h2><div className="mt-5 space-y-5">{[["Servo Stabilizer 10KVA", "46 orders", 92], ["MCC Control Panel", "28 orders", 72], ["Isolation Transformer", "21 orders", 58], ["APFC Panel", "17 orders", 44]].map(([name, orders, value]) => <div key={String(name)}><div className="flex justify-between text-xs"><span className="text-slate-300">{name}</span><span className="text-slate-600">{orders}</span></div><div className="mt-2 h-1.5 rounded-full bg-slate-800"><div className="h-full rounded-full bg-blue-500" style={{ width: `${value}%` }} /></div></div>)}</div></Card>;
}

const tableContent: Record<string, { title: string; action: string; headers: string[]; rows: string[][] }> = {
  products: { title: "Product inventory", action: "Add product", headers: ["Product", "SKU", "Category", "Price", "Stock", "Status"], rows: [["Servo Stabilizer 10KVA", "PM-SVS-010", "Stabilizers", "₹45,000", "18", "Active"], ["MCC Control Panel 125A", "PM-MCC-125", "Control Panels", "₹1,20,000", "Made to order", "Active"], ["Isolation Transformer 25KVA", "PM-IT-025", "Transformers", "₹32,000", "7", "Active"], ["Online UPS 20KVA", "PM-UPS-020", "UPS Systems", "₹1,65,000", "4", "Low stock"]] },
  orders: { title: "Order management", action: "Export orders", headers: ["Order", "Customer", "Date", "Items", "Total", "Status"], rows: [["PM-260614", "ABC Textiles", "14 Jun", "1", "₹53,100", "Processing"], ["PM-260613", "NovaCare Hospitals", "13 Jun", "10", "₹3,77,600", "Confirmed"], ["PM-260611", "Orion Foods", "11 Jun", "1", "₹1,05,020", "Dispatched"], ["PM-260608", "Axion Auto", "8 Jun", "3", "₹4,72,000", "Delivered"]] },
  customers: { title: "Customer accounts", action: "Add customer", headers: ["Company", "Contact", "Industry", "Orders", "Lifetime value", "Status"], rows: [["ABC Textiles", "Rajesh Sharma", "Textiles", "12", "₹18,40,000", "Active"], ["NovaCare Hospitals", "Dr. Amit Mehra", "Healthcare", "8", "₹24,70,000", "Active"], ["Orion Foods", "Neha Kulkarni", "Food Processing", "6", "₹9,35,000", "Active"], ["Axion Auto", "S. Desai", "Automotive", "4", "₹13,20,000", "Key account"]] },
  quotes: { title: "Quote pipeline", action: "Create quote", headers: ["Quote", "Company", "Requirement", "Value", "Owner", "Stage"], rows: [["PMQ-102441", "ABC Textiles", "MCC Panel", "₹4,80,000", "A. Kapoor", "Technical review"], ["PMQ-102438", "Vertex Data", "UPS System", "₹12,40,000", "N. Shah", "Proposal sent"], ["PMQ-102432", "CityCare", "Isolation package", "₹7,80,000", "A. Kapoor", "Negotiation"], ["PMQ-102425", "Innova Tools", "Servo Stabilizer", "₹2,20,000", "R. Patil", "Won"]] },
  leads: { title: "Lead pipeline", action: "Add lead", headers: ["Lead", "Company", "Source", "Score", "Requirement", "Status"], rows: [["LD-6214", "Metro Labs", "Google", "92", "20KVA UPS", "Qualified"], ["LD-6213", "Shakti Polymers", "Referral", "84", "APFC Panel", "Contacted"], ["LD-6211", "Arion Systems", "Website", "76", "PCC Panel", "New"], ["LD-6208", "Bright Campus", "Instagram", "62", "Stabilizer", "Nurture"]] },
};

export function AdminTablePage({ type }: { type: keyof typeof tableContent }) {
  const data = tableContent[type];
  return <div><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-bold text-white">{data.title}</h2><p className="mt-1 text-xs text-slate-600">Live operational view with searchable records.</p></div><Button>{data.action}</Button></div><Card className="mt-6 overflow-hidden"><div className="flex gap-2 border-b border-line p-4"><div className="relative max-w-sm flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-600" /><Input className="pl-9" placeholder={`Search ${type}`} /></div><select className="rounded-xl border border-line bg-slate-950 px-3 text-xs text-slate-400"><option>All statuses</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="border-b border-line bg-slate-950/50 text-xs text-slate-600"><tr>{data.headers.map((h) => <th key={h} className="px-5 py-4">{h}</th>)}</tr></thead><tbody>{data.rows.map((row) => <tr key={row[0]} className="border-b border-line last:border-0 hover:bg-slate-800/30">{row.map((cell, index) => <td key={cell} className={`px-5 py-5 ${index === 0 ? "font-bold text-white" : index === row.length - 1 ? "text-emerald-400" : "text-slate-500"}`}>{cell}</td>)}</tr>)}</tbody></table></div></Card></div>;
}

export function AnalyticsPage() {
  return <div><div className="grid gap-4 sm:grid-cols-3">{[["Conversion rate", "8.4%", "+1.2%"], ["Average order value", "₹2,03,804", "+6.5%"], ["Customer retention", "71%", "+4.1%"]].map(([label, value, change]) => <Card key={label} className="p-5"><p className="text-xs text-slate-600">{label}</p><p className="mt-2 text-2xl font-extrabold text-white">{value}</p><p className="mt-2 text-xs text-emerald-400">{change} vs prior period</p></Card>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_.6fr]"><RevenueChart /><Card className="p-6"><h2 className="font-bold text-white">Traffic sources</h2><div className="mt-6 space-y-5">{[["Organic Search", 42, "bg-blue-500"], ["Direct", 28, "bg-emerald-500"], ["Paid Campaigns", 18, "bg-orange-500"], ["Social & Referral", 12, "bg-violet-500"]].map(([name, value, color]) => <div key={String(name)}><div className="flex justify-between text-xs"><span>{name}</span><span>{value}%</span></div><div className="mt-2 h-2 rounded-full bg-slate-800"><div className={`h-full rounded-full ${color}`} style={{ width: `${value}%` }} /></div></div>)}</div></Card></div><div className="mt-5 grid gap-5 md:grid-cols-2"><Card className="p-6"><h2 className="font-bold text-white">Lead funnel</h2>{[["Website sessions", 12480, 100], ["Product views", 6420, 72], ["Enquiries", 834, 48], ["Qualified leads", 326, 28], ["Orders", 184, 16]].map(([name, value, width]) => <div key={String(name)} className="mt-5"><div className="flex justify-between text-xs text-slate-500"><span>{name}</span><span>{Number(value).toLocaleString("en-IN")}</span></div><div className="mt-2 h-3 rounded bg-slate-800"><div className="h-full rounded bg-gradient-to-r from-blue-700 to-blue-400" style={{ width: `${width}%` }} /></div></div>)}</Card><TopProducts /></div></div>;
}

export function TargetsPage() {
  const periods = [["Monthly", 5000000, 3750000], ["Quarterly", 14000000, 11200000], ["Yearly", 50000000, 34800000]];
  return <div><div className="grid gap-4 sm:grid-cols-3">{[["Target Revenue", "₹5,00,00,000", "FY 2025–26"], ["Achieved Revenue", "₹3,48,00,000", "69.6% complete"], ["Remaining Revenue", "₹1,52,00,000", "107 days remaining"]].map(([label, value, sub], index) => <Card key={label} className="p-5"><span className={`grid h-10 w-10 place-items-center rounded-xl ${index === 1 ? "bg-emerald-500/10 text-emerald-400" : index === 2 ? "bg-orange-500/10 text-orange-400" : "bg-blue-500/10 text-blue-400"}`}><TrendingUp className="h-5 w-5" /></span><p className="mt-5 text-xs text-slate-600">{label}</p><p className="mt-2 text-2xl font-extrabold text-white">{value}</p><p className="mt-2 text-xs text-slate-500">{sub}</p></Card>)}</div><Card className="mt-5 p-6"><h2 className="font-bold text-white">Target progress</h2><div className="mt-7 space-y-8">{periods.map(([name, target, achieved]) => { const percent = Math.round(Number(achieved) / Number(target) * 100); return <div key={String(name)}><div className="flex items-end justify-between"><div><p className="font-bold text-white">{name}</p><p className="mt-1 text-xs text-slate-600">{formatCurrency(Number(achieved))} of {formatCurrency(Number(target))}</p></div><strong className="text-blue-400">{percent}%</strong></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-gradient-to-r from-blue-700 to-cyan-400" style={{ width: `${percent}%` }} /></div></div>; })}</div></Card><div className="mt-5 grid gap-5 lg:grid-cols-2"><RevenueChart /><Card className="p-6"><h2 className="font-bold text-white">Team contribution</h2><div className="mt-6 space-y-5">{[["Aarav Kapoor", "West region", 88], ["Nisha Shah", "North region", 76], ["Rohan Patil", "South region", 68], ["Meera Iyer", "Key accounts", 92]].map(([name, region, percent]) => <div key={String(name)}><div className="flex justify-between"><div><p className="text-sm font-semibold text-white">{name}</p><p className="text-[11px] text-slate-600">{region}</p></div><strong className="text-sm text-blue-400">{percent}%</strong></div><div className="mt-2 h-1.5 rounded-full bg-slate-800"><div className="h-full rounded-full bg-blue-500" style={{ width: `${percent}%` }} /></div></div>)}</div></Card></div></div>;
}

export function SettingsPage() {
  return <div className="max-w-3xl"><h2 className="text-xl font-bold text-white">Workspace settings</h2><p className="mt-1 text-xs text-slate-600">Configure storefront and operational preferences.</p><div className="mt-6 space-y-5"><Card className="p-6"><h3 className="font-bold text-white">Company profile</h3><div className="mt-5 grid gap-4 sm:grid-cols-2"><Input defaultValue="PaceMaker Electricals" /><Input defaultValue="projects@pacemakerelectric.com" /><Input defaultValue="+91 98765 43210" /><Input defaultValue="GSTIN 27AAECP0000A1Z5" /></div></Card><Card className="p-6"><h3 className="font-bold text-white">Notifications</h3><div className="mt-5 space-y-4">{["New order alerts", "High-value lead alerts", "Low stock alerts", "Daily revenue summary"].map((item) => <label key={item} className="flex items-center justify-between text-sm text-slate-400"><span>{item}</span><input type="checkbox" defaultChecked className="h-4 w-4 accent-blue-600" /></label>)}</div></Card><Button>Save settings</Button></div></div>;
}
