import { useMemo, useState, type FormEvent } from "react";
import { ArrowRight, CheckCircle2, CreditCard, Heart, MapPin, Minus, PackageCheck, Plus, ShieldCheck, ShoppingBag, Trash2 } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { ProductCard } from "../components/ProductCard";
import { Button, Card, Input, SectionHeading } from "../components/ui";
import { useStore } from "../context/StoreContext";
import { formatCurrency } from "../lib/utils";

export function CartPage() {
  const { cart, removeFromCart, updateQuantity } = useStore();
  const subtotal = cart.reduce((sum, item) => sum + item.product.price * item.quantity, 0);
  const gst = Math.round(subtotal * .18);
  return <div className="page-shell section-pad"><SectionHeading eyebrow="Shopping Cart" title={cart.length ? "Review your equipment" : "Your cart is empty"} description={cart.length ? "Shipping and final application details are confirmed before dispatch." : "Explore the catalog or request a custom engineering quote."} />{cart.length ? <div className="mt-10 grid gap-8 lg:grid-cols-[1fr_380px]"><div className="space-y-4">{cart.map(({ product, quantity }) => <Card key={product.id} className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center"><div className="grid h-24 w-full place-items-center rounded-xl bg-blue-500/10 text-blue-400 sm:w-24"><ShoppingBag className="h-8 w-8" /></div><div className="flex-1"><Link to={`/products/${product.slug}`} className="font-bold text-white hover:text-blue-400">{product.name}</Link><p className="mt-1 text-xs text-slate-500">{product.capacity} · {product.phase} · {product.stock}</p><p className="mt-3 font-bold text-orange-500">{product.priceLabel}</p></div><div className="flex items-center justify-between gap-3"><span className="flex h-10 items-center rounded-lg border border-line"><button onClick={() => updateQuantity(product.id, quantity - 1)} className="px-3"><Minus className="h-3 w-3" /></button><span className="w-6 text-center text-sm text-white">{quantity}</span><button onClick={() => updateQuantity(product.id, quantity + 1)} className="px-3"><Plus className="h-3 w-3" /></button></span><button onClick={() => removeFromCart(product.id)} className="p-2 text-slate-500 hover:text-red-400" aria-label="Remove"><Trash2 className="h-5 w-5" /></button></div></Card>)}</div><OrderSummary subtotal={subtotal} gst={gst} /></div> : <Card className="mt-10 py-20 text-center"><ShoppingBag className="mx-auto h-12 w-12 text-slate-700" /><Link to="/products"><Button className="mt-6">Explore products <ArrowRight className="h-4 w-4" /></Button></Link></Card>}</div>;
}

function OrderSummary({ subtotal, gst }: { subtotal: number; gst: number }) {
  return <Card className="h-fit p-6"><h2 className="text-lg font-bold text-white">Order summary</h2><div className="mt-6 space-y-3 text-sm"><div className="flex justify-between text-slate-400"><span>Subtotal</span><span>{formatCurrency(subtotal)}</span></div><div className="flex justify-between text-slate-400"><span>GST (18%)</span><span>{formatCurrency(gst)}</span></div><div className="flex justify-between text-slate-400"><span>Shipping</span><span className="text-emerald-400">Calculated next</span></div><div className="border-t border-line pt-4"><div className="flex justify-between text-lg font-bold text-white"><span>Total</span><span>{formatCurrency(subtotal + gst)}</span></div><p className="mt-2 text-xs text-slate-600">Inclusive of applicable taxes</p></div></div><Link to="/checkout"><Button size="lg" className="mt-6 w-full">Proceed to checkout <ArrowRight className="h-4 w-4" /></Button></Link><div className="mt-5 flex items-center justify-center gap-2 text-xs text-slate-500"><ShieldCheck className="h-4 w-4 text-emerald-400" />Secure order review</div></Card>;
}

export function CheckoutPage() {
  const { cart, notify } = useStore();
  const navigate = useNavigate();
  const [complete, setComplete] = useState(false);
  const subtotal = cart.reduce((sum, item) => sum + item.product.price * item.quantity, 0);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setComplete(true); notify("Payment authorized successfully"); window.setTimeout(() => navigate("/orders"), 1800); }
  if (!cart.length && !complete) return <div className="page-shell section-pad"><Card className="py-20 text-center"><h1 className="text-2xl font-bold text-white">There is nothing to check out yet</h1><Link to="/products"><Button className="mt-6">Browse products</Button></Link></Card></div>;
  if (complete) return <div className="page-shell section-pad"><Card className="mx-auto max-w-xl py-16 text-center"><CheckCircle2 className="mx-auto h-16 w-16 text-emerald-400" /><h1 className="mt-6 text-3xl font-bold text-white">Order confirmed</h1><p className="mt-3 text-slate-500">Order PM-260614 has been created. Redirecting to order tracking…</p></Card></div>;
  return <div className="page-shell section-pad"><SectionHeading eyebrow="Secure Checkout" title="Delivery and payment" description="Your application and delivery details will be reviewed before final dispatch." /><form onSubmit={submit} className="mt-10 grid gap-8 lg:grid-cols-[1fr_380px]"><div className="space-y-5"><Card className="p-6"><h2 className="flex items-center gap-2 font-bold text-white"><MapPin className="h-5 w-5 text-blue-400" />Delivery address</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Input placeholder="Full name" required /><Input placeholder="Company" required /><Input type="tel" placeholder="Phone" required /><Input type="email" placeholder="Email" required /><Input placeholder="Address line" className="sm:col-span-2" required /><Input placeholder="City" required /><Input placeholder="PIN code" required /></div></Card><Card className="p-6"><h2 className="flex items-center gap-2 font-bold text-white"><CreditCard className="h-5 w-5 text-blue-400" />Payment method</h2><div className="mt-5 grid gap-3 sm:grid-cols-3">{["UPI", "Credit / Debit Card", "Net Banking / EMI"].map((method, index) => <label key={method} className="flex cursor-pointer items-center gap-3 rounded-xl border border-line p-4 text-sm text-slate-300 has-[:checked]:border-blue-500 has-[:checked]:bg-blue-500/10"><input type="radio" name="payment" defaultChecked={index === 0} className="accent-blue-600" />{method}</label>)}</div><Input className="mt-4" placeholder="UPI ID (example@bank)" required /></Card></div><Card className="h-fit p-6"><h2 className="font-bold text-white">Payable amount</h2><div className="mt-5 space-y-3 text-sm text-slate-400"><div className="flex justify-between"><span>Equipment</span><span>{formatCurrency(subtotal)}</span></div><div className="flex justify-between"><span>GST</span><span>{formatCurrency(subtotal * .18)}</span></div><div className="flex justify-between border-t border-line pt-4 text-lg font-bold text-white"><span>Total</span><span>{formatCurrency(subtotal * 1.18)}</span></div></div><Button type="submit" size="lg" className="mt-6 w-full">Pay securely</Button><p className="mt-4 text-center text-xs leading-5 text-slate-600">UPI, cards, net banking and EMI supported through secure payment processing.</p></Card></form></div>;
}

export function WishlistPage() {
  const { wishlist } = useStore();
  return <div className="page-shell section-pad"><SectionHeading eyebrow="Saved Products" title="Your wishlist" description="Keep shortlisted equipment together while your technical team compares options." />{wishlist.length ? <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{wishlist.map((product) => <ProductCard key={product.id} product={product} />)}</div> : <Card className="mt-10 py-20 text-center"><Heart className="mx-auto h-12 w-12 text-slate-700" /><p className="mt-4 text-slate-500">No products saved yet.</p><Link to="/products"><Button className="mt-6">Explore products</Button></Link></Card>}</div>;
}
