import { useState, type FormEvent, type ReactNode } from "react";
import { ArrowRight, Building2, Check, ChevronDown, Factory, Gauge, HeartPulse, Mail, MapPin, MessageCircle, Phone, Send, Server, ShieldCheck, Target, Users, Zap } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { Button, Card, Input, SectionHeading, Textarea } from "../components/ui";
import { useStore } from "../context/StoreContext";

const solutions = [
  ["Voltage Regulation", "Protect sensitive equipment from sags, surges and unstable utility supply with precision servo control.", "Servo stabilizers, static stabilizers, buck-boost systems"],
  ["Power Distribution", "Safe, maintainable LV distribution engineered around your SLD, fault levels and future expansion.", "PCC, MCC, distribution and synchronizing panels"],
  ["Power Quality", "Reduce harmonic stress, reactive demand and avoidable utility penalties with measured correction.", "APFC panels, harmonic filters, capacitor banks"],
  ["Critical Power", "Maintain clean, uninterrupted power for process controls, healthcare systems and IT infrastructure.", "Online UPS, isolation transformers, battery systems"],
  ["Industrial Automation", "Improve process visibility and repeatability with integrated PLC, HMI and SCADA control.", "PLC panels, VFD panels, remote monitoring"],
  ["Custom Engineering", "Turn site constraints and detailed specifications into tested, documented electrical assemblies.", "Application studies, custom builds, turnkey execution"],
];

const industryData = [
  [Factory, "Manufacturing", "CNC machines, process lines, motors and automation require stable voltage and coordinated protection."],
  [HeartPulse, "Healthcare", "Diagnostic imaging, laboratories and critical care demand clean, isolated and uninterrupted power."],
  [Server, "Data Centers", "Conditioning, bypass and monitoring architectures support high availability across critical compute loads."],
  [Building2, "Commercial Infrastructure", "Efficient LV distribution and power factor correction reduce operating costs at scale."],
  [Gauge, "Automotive", "Welding, robotics and precision machining benefit from tightly regulated voltage and intelligent control."],
  [Users, "Education & Research", "Campus utilities and sensitive laboratories need dependable, maintainable electrical systems."],
];

const studies = [
  { slug: "textile-plant-voltage-stability", industry: "Textile Manufacturing", title: "86 looms protected from chronic voltage fluctuation", summary: "A centralized 500 KVA servo stabilizer reduced electrical downtime by 18% and eliminated drive trips.", metric: "18%", label: "less downtime" },
  { slug: "hospital-clean-power", industry: "Healthcare", title: "Clean power for a multi-speciality hospital expansion", summary: "Isolation and online UPS systems protected radiology, laboratory and critical care equipment across a new wing.", metric: "99.99%", label: "critical uptime" },
  { slug: "automotive-power-factor", industry: "Automotive Components", title: "Reactive demand penalties removed in eleven months", summary: "A detuned APFC architecture stabilized power factor under rapidly changing welding and motor loads.", metric: "11 mo", label: "project payback" },
];

const posts = [
  { slug: "selecting-servo-stabilizer", date: "June 8, 2026", title: "How to size a servo voltage stabilizer for an industrial load", excerpt: "A practical capacity calculation covering motor starts, diversity, input range and future expansion." },
  { slug: "apfc-panel-roi", date: "May 21, 2026", title: "Calculating the ROI of an APFC panel", excerpt: "Translate reactive demand, utility penalties and operating hours into a defensible payback estimate." },
  { slug: "panel-fat-checklist", date: "April 30, 2026", title: "The essential factory acceptance test checklist for LV panels", excerpt: "What project and maintenance teams should verify before a panel leaves the manufacturing floor." },
];

function PageHero({ eyebrow, title, text, children }: { eyebrow: string; title: string; text: string; children?: ReactNode }) {
  return <section className="relative overflow-hidden border-b border-line industrial-grid"><div className="absolute inset-0 bg-gradient-to-b from-blue-950/20 to-ink" /><div className="page-shell relative py-20 text-center sm:py-28"><p className="text-xs font-bold uppercase tracking-[.25em] text-blue-400">{eyebrow}</p><h1 className="mx-auto mt-5 max-w-4xl text-4xl font-extrabold tracking-tight text-white sm:text-6xl">{title}</h1><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-slate-400 sm:text-lg">{text}</p>{children}</div></section>;
}

export function CategoriesPage() {
  return <><PageHero eyebrow="Catalog" title="One system. Every power requirement." text="Browse engineered product families for voltage control, distribution, power quality and automation." /><section className="page-shell section-pad"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{solutions.map(([title, text, list], index) => <Link to={`/products?q=${encodeURIComponent(title)}`} key={title}><Card className="group h-full p-6 transition hover:-translate-y-1 hover:border-blue-500/50"><span className="grid h-12 w-12 place-items-center rounded-xl bg-blue-500/10 text-blue-400"><Zap className="h-6 w-6" /></span><p className="mt-5 text-xs font-bold text-orange-500">0{index + 1}</p><h2 className="mt-2 text-xl font-bold text-white">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-500">{text}</p><p className="mt-5 border-t border-line pt-4 text-xs text-slate-400">{list}</p></Card></Link>)}</div></section></>;
}

export function SolutionsPage() {
  const { openQuote } = useStore();
  return <><PageHero eyebrow="Engineering Solutions" title="Built around the load, not a brochure" text="We study the application, model the operating conditions and deliver a coordinated system with one accountable team."><Button className="mt-8" size="lg" onClick={() => openQuote()}>Discuss your application <ArrowRight className="h-5 w-5" /></Button></PageHero><section className="page-shell section-pad"><div className="space-y-4">{solutions.map(([title, text, list], index) => <Card key={title} className="grid gap-5 p-6 md:grid-cols-[80px_1fr_1fr] md:items-center"><span className="text-3xl font-extrabold text-blue-500/50">0{index + 1}</span><div><h2 className="text-xl font-bold text-white">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div><div className="rounded-xl bg-slate-950/60 p-4 text-sm text-slate-300">{list}</div></Card>)}</div></section></>;
}

export function IndustriesPage() {
  return <><PageHero eyebrow="Industries" title="Designed for where downtime is expensive" text="Domain-aware electrical engineering for facilities where stability, safety and service response matter." /><section className="page-shell section-pad"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{industryData.map(([Icon, title, text]) => <Card key={String(title)} className="p-6"><Icon className="h-8 w-8 text-blue-400" /><h2 className="mt-6 text-xl font-bold text-white">{String(title)}</h2><p className="mt-3 text-sm leading-6 text-slate-500">{String(text)}</p><Link to="/contact" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-blue-400">Plan a solution <ArrowRight className="h-4 w-4" /></Link></Card>)}</div></section></>;
}

export function CaseStudiesPage() {
  return <><PageHero eyebrow="Case Studies" title="Results measured in uptime" text="A closer look at the constraints, engineering decisions and operational outcomes behind selected projects." /><section className="page-shell section-pad"><div className="grid gap-5 lg:grid-cols-3">{studies.map((study) => <Card key={study.slug} className="overflow-hidden"><div className="industrial-grid h-40 border-b border-line bg-blue-950/20 p-6"><span className="text-xs font-bold uppercase tracking-widest text-blue-400">{study.industry}</span><p className="mt-5 text-4xl font-extrabold text-orange-500">{study.metric}</p><p className="text-xs text-slate-500">{study.label}</p></div><div className="p-6"><h2 className="text-xl font-bold text-white">{study.title}</h2><p className="mt-3 text-sm leading-6 text-slate-500">{study.summary}</p><Link to="/contact" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-blue-400">Request project brief <ArrowRight className="h-4 w-4" /></Link></div></Card>)}</div></section></>;
}

export function AboutPage() {
  return <><PageHero eyebrow="About PaceMaker" title="Industrial power, engineered with care" text="For more than fifteen years, PaceMaker has helped Indian businesses protect equipment, improve power quality and build dependable electrical infrastructure." /><section className="page-shell section-pad"><div className="grid gap-10 lg:grid-cols-2 lg:items-center"><div><SectionHeading eyebrow="Our Standard" title="Every system leaves the floor proven" description="Our engineering and production teams own the complete lifecycle from application study and design through manufacturing, FAT, commissioning and service." /><div className="mt-7 space-y-3">{["ISO 9001:2015 quality management", "Documented stage inspection and final testing", "Approved component ecosystems", "Pan-India installation and lifecycle support"].map((item) => <p key={item} className="flex items-center gap-3 text-sm text-slate-300"><Check className="h-4 w-4 text-emerald-400" />{item}</p>)}</div></div><div className="grid grid-cols-2 gap-4">{[["15+", "Years"], ["5000+", "Installations"], ["1000+", "Clients"], ["25+", "Service cities"]].map(([value, label]) => <Card key={label} className="p-6 text-center"><strong className="text-3xl text-blue-500 sm:text-4xl">{value}</strong><p className="mt-2 text-sm text-slate-500">{label}</p></Card>)}</div></div></section><section className="border-y border-line bg-[#050a15]"><div className="page-shell section-pad grid gap-4 md:grid-cols-3">{[[Target, "Mission", "Make industrial-grade power quality accessible through disciplined engineering and responsive service."], [ShieldCheck, "Quality", "Build equipment that performs predictably through real electrical and environmental stress."], [Users, "Partnership", "Stay accountable after dispatch, with clear communication and practical field support."]].map(([Icon, title, text]) => <Card key={String(title)} className="p-6"><Icon className="h-7 w-7 text-blue-400" /><h2 className="mt-5 text-xl font-bold text-white">{String(title)}</h2><p className="mt-3 text-sm leading-6 text-slate-500">{String(text)}</p></Card>)}</div></section></>;
}

export function ContactPage() {
  const { notify } = useStore();
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); event.currentTarget.reset(); notify("Message sent. Our engineering team will contact you shortly."); }
  return <><PageHero eyebrow="Contact" title="Talk to a power systems engineer" text="Share your application, load details or drawing. We will help define the right equipment and next steps." /><section className="page-shell section-pad grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div className="space-y-4">{[[Phone, "Call", "+91 98765 43210", "tel:+919876543210"], [Mail, "Email", "projects@pacemakerelectric.com", "mailto:projects@pacemakerelectric.com"], [MessageCircle, "WhatsApp", "Chat with an engineer", "https://wa.me/919876543210"], [MapPin, "Factory", "Pune, Maharashtra, India", "#"]].map(([Icon, label, value, href]) => <a key={String(label)} href={String(href)}><Card className="mb-4 flex items-center gap-4 p-5"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-500/10 text-blue-400"><Icon className="h-5 w-5" /></span><div><p className="text-xs text-slate-500">{String(label)}</p><p className="mt-1 text-sm font-semibold text-white">{String(value)}</p></div></Card></a>)}</div><Card className="p-6 sm:p-8"><h2 className="text-2xl font-bold text-white">Project enquiry</h2><p className="mt-2 text-sm text-slate-500">Typical response time: under one business day.</p><form onSubmit={submit} className="mt-7 space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Input placeholder="Full name" required /><Input placeholder="Company" required /></div><div className="grid gap-4 sm:grid-cols-2"><Input type="email" placeholder="Work email" required /><Input type="tel" placeholder="Phone number" required /></div><select className="h-11 w-full rounded-xl border border-line bg-slate-950/70 px-4 text-sm text-slate-400 outline-none focus:border-blue-500" required><option value="">Select requirement</option><option>Servo stabilizer</option><option>Control panel</option><option>Transformer / UPS</option><option>Power quality study</option><option>Service support</option></select><Textarea placeholder="Describe load, capacity, input range and delivery location" required /><Button type="submit" className="w-full sm:w-auto"><Send className="h-4 w-4" />Send enquiry</Button></form></Card></section></>;
}

export function BlogPage() {
  return <><PageHero eyebrow="Knowledge Center" title="Practical electrical engineering" text="Guides and field notes for project, plant and maintenance teams." /><section className="page-shell section-pad"><div className="grid gap-5 lg:grid-cols-3">{posts.map((post, index) => <Card key={post.slug} className="overflow-hidden"><div className={`h-44 industrial-grid ${index === 1 ? "bg-orange-950/20" : index === 2 ? "bg-emerald-950/20" : "bg-blue-950/20"}`} /><div className="p-6"><p className="text-xs text-blue-400">{post.date}</p><h2 className="mt-3 text-xl font-bold leading-snug text-white">{post.title}</h2><p className="mt-3 text-sm leading-6 text-slate-500">{post.excerpt}</p><Link to={`/blog/${post.slug}`} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-blue-400">Read guide <ArrowRight className="h-4 w-4" /></Link></div></Card>)}</div></section></>;
}

export function BlogDetailPage() {
  const { slug } = useParams();
  const post = posts.find((item) => item.slug === slug) || posts[0];
  return <article><PageHero eyebrow={post.date} title={post.title} text={post.excerpt} /><div className="mx-auto max-w-3xl px-5 py-16 text-base leading-8 text-slate-400"><p>Industrial electrical equipment should be sized from measured operating conditions, not nameplate totals alone. Start with the steady-state connected load, then identify motors, compressors, welding systems and other equipment with high inrush or rapidly varying demand.</p><h2 className="mt-10 text-2xl font-bold text-white">Start with the operating envelope</h2><p className="mt-4">Record minimum and maximum incoming voltage, phase imbalance, typical load, peak load and expected expansion. The required equipment capacity is affected by each of these factors, along with ambient temperature and installation conditions.</p><div className="my-8 rounded-2xl border border-blue-500/30 bg-blue-500/10 p-6 text-blue-200">A 20–25% engineering margin is common, but large motor starts or unusually wide input ranges may require a different selection.</div><h2 className="mt-10 text-2xl font-bold text-white">Validate protection and bypass</h2><p className="mt-4">Capacity is only one part of a reliable design. Confirm overload behavior, short-circuit coordination, high/low voltage cut-off, bypass arrangements, metering and service access before approving the system.</p><p className="mt-6">For critical applications, share your single-line diagram and load schedule with a qualified application engineer before procurement.</p></div></article>;
}

export function FaqPage() {
  const [active, setActive] = useState(0);
  const items = [
    ["Which stabilizer technology is best for industrial use?", "Servo stabilizers suit most industrial loads that need precise regulation over a wide input range. Static stabilizers are preferred where very fast correction is essential."],
    ["Do your panels comply with IEC standards?", "Yes. Assemblies are designed and tested against applicable IEC practices, with documented drawings, BOMs, routine tests and project-specific compliance requirements."],
    ["Can you supply equipment anywhere in India?", "Yes. We dispatch nationwide and provide installation, commissioning and service support in major industrial regions."],
    ["Are products available with copper winding?", "Yes. Copper construction is standard or optional depending on the product family and project specification."],
    ["Can I buy online and still receive engineering support?", "Yes. Orders are reviewed for application fit, and an engineer contacts you when a capacity or specification detail needs confirmation."],
    ["How are warranty claims handled?", "Raise a support ticket with the serial number and operating details. Remote diagnosis begins immediately, followed by parts or site service where required."],
  ];
  return <><PageHero eyebrow="Support" title="Frequently asked questions" text="Clear answers on selection, ordering, delivery and service." /><section className="mx-auto max-w-4xl px-5 py-16"><div className="divide-y divide-line rounded-2xl border border-line bg-panel">{items.map(([q, a], index) => <div key={q}><button onClick={() => setActive(active === index ? -1 : index)} className="flex w-full items-center justify-between p-5 text-left font-semibold text-white">{q}<ChevronDown className={`h-5 w-5 transition ${active === index ? "rotate-180" : ""}`} /></button>{active === index && <p className="px-5 pb-5 text-sm leading-7 text-slate-400">{a}</p>}</div>)}</div></section></>;
}

export function LegalPage({ type }: { type: "privacy" | "terms" }) {
  const privacy = type === "privacy";
  return <><PageHero eyebrow="Legal" title={privacy ? "Privacy Policy" : "Terms of Service"} text={`Effective June 14, 2026. ${privacy ? "How PaceMaker collects, uses and protects your information." : "The terms governing use of our website, quotations and online ordering services."}`} /><section className="mx-auto max-w-3xl px-5 py-16 text-sm leading-7 text-slate-400"><h2 className="text-xl font-bold text-white">{privacy ? "Information we collect" : "Use of this website"}</h2><p className="mt-4">{privacy ? "We collect information you provide through account registration, enquiries, quote requests, purchases and support interactions. We also collect limited technical information required to operate and secure the service." : "Product information is provided for planning and procurement. Final suitability remains subject to application review, approved specifications and commercial terms stated in the quotation or order confirmation."}</p><h2 className="mt-9 text-xl font-bold text-white">{privacy ? "How information is used" : "Orders and quotations"}</h2><p className="mt-4">{privacy ? "Information is used to respond to enquiries, process orders, deliver support, improve services and meet legal obligations. We do not sell personal data." : "Prices, lead times and availability may change until an order is confirmed. Custom-built equipment enters production after technical and commercial approval and may have different cancellation conditions."}</p><h2 className="mt-9 text-xl font-bold text-white">Contact</h2><p className="mt-4">Questions may be sent to legal@pacemakerelectric.com.</p></section></>;
}
